# Welcome to Jekyll!
#

# Site settings
theme: jekyll-theme-hacker

title: Kamil Vavra | @vavkamil
description: Offensive Web Application Security | Ethical Hacking | Security Research

twitter:
  username: vavkamil
  card: summary

author: "vavkamil"

social:
  name: Kamil Vavra
  links:
    - https://twitter.com/vavkamil
    - https://linkedin.com/in/vavkamil
    - https://github.com/vavkamil
    - https://reddit.com/u/_vavkamil_


# Plugins
plugins:
 - jekyll-sitemap
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-gist
 - jekyll-redirect-from

# SEO
permalink: /blog/:year-:month-:day-:title/

# Collections
collections:
  blog_categories:
    output: true
    permalink: /blog/category/:name/
  talks:
    output: true
    permalink: /talks/:name/

